### ISSUE TITLE
Update British Library (simplified) XSLT

### ISSUE THREAD

**Issue by alexandermendes** [alexandermendes/tei-viewer#15]
Add the following columns:
- Physical Description: `<physDesc>` (whatever is within `<p></p>` tags)
- Handwriting: `<handDesc>` (`<summary>` tags)
- Scribe: `<name role="scribe">`
- Author: `<author>`

And in the ‘Related People’ column not include the scribe, but only `<name role="owner">`, `<name role="bookseller">`, `<name role="censor">.`

**Comment by adikeinan** [comment]
Since there will be an option to choose a full view of the records, I'd cut down the following fields from the simplified version:
- Dimensions
- Acqusition
- Related People (after creating separate fields for author and scribe)
- Related Places

**Comment by alexandermendes** [comment]
Updates made! Let me know if you need any further changes.

**Comment by adikeinan** [comment]
Looking great, thank you!
