### ISSUE TITLE
Table navigation

### ISSUE THREAD

**Issue by adikeinan** [alexandermendes/tei-viewer#16]
Not sure this is possible, but is there a way to:
1. Freeze the header line?
2. Make a horizontal scroll bar always visible (rather than having to scroll sideways with the mouse, or scrolling all the way down to view the scroll bar)?

**Comment by alexandermendes** [comment]
Freezing the table header turned out to be a bit tricky but got there in the end!

**Comment by adikeinan** [comment]
Thanks, it looks really great now!
