### ISSUE TITLE
Update British Library full Hebrew XSLT

### ISSUE THREAD

**Issue by adikeinan** [alexandermendes/tei-viewer#18]
Here are the fields that need to be included in the full XSLT for Hebrew manuscripts (label: XML field):
- Decorations - Initial words: `<decoNote type="initial">` (inc. `<locus n>`)
- Decorations - Miniatures: `<decoNote type="miniature">` (inc. `<locus n>`)
- Decorations - Illustrations: `<decoNote type="illustration">` (inc. `<locus n>`)
- Decorations - Paratext: `<decoNote type="paratext">` (inc. `<locus n>`)
- Decorations - Borders: `<decoNote type="border">` (inc. `<locus n>`)
- Decorations - Other: `<decoNote type="other">` (inc. `<locus n>`)
- Colphon: `<colophon>` (inc. `<locus n>`)
- Comments: `<note></note>` (this may include useful comments and bibliography - the latter sometimes [though not always] within `<listBibl>` tags)
- Detailed Contents: `<msItem rend="v">` (inc. `<locus to + from>`, `<title>`, `<note>`; may also include `<author>`, `<filiation>`, `<quote>`; this is a detailed breakdown of the manuscript's content into sections)
- Material: `<supportDesc>`
- Collation: `<collation>`
- Condition: `<condition>`
- Layout: `<layoutDesc>`
- Script: `<handDesc>` inc. Number of Scribes (e.g. hands="2"), `<handNote>`, `<p>``</p>` for more details (I previously labelled this field as 'Handwriting'; 'Script' is actually a better label)
- Additions: `<additions>`
- Binding: `<bindingDesc>`
- Record History: `<recordHist>`
- Margoliouth ID: `<bibl>``<ref type="number" target="Margoliouth_1965">` (most of our currently digitised manuscripts have been catalogued in the 19th century. This field indicated the manuscript's ID number in the printed catalogue by George Margoliouth)

**Comment by alexandermendes** [comment]
[sample records.zip](https://github.com/alexandermendes/tei-viewer/files/285061/sample.records.zip)

**Comment by alexandermendes** [comment]
Full version added. Again, let me know if you spot any places where we could improve the formatting etc.

**Comment by adikeinan** [comment]
Thanks!
The field 'Colphon' should read 'Colophon' (sorry, my bad!)
In addition, the full version should include a couple of fields that we removed from the simple version:
- Dimensions
- Acquisition
- Related People (except for authors and scribes)
- Related Places

**Comment by adikeinan** [comment]
Oh sorry, I now see that dimensions are included in 'Extent' - so no need for that.

**Comment by alexandermendes** [comment]
Oops, actually spotted the colophon but apparently didn't correct it. Have added the other columns.

**Comment by adikeinan** [comment]
Thanks! In a previous version you added the role of each 'related person' in brackets, e.g. bookseller or owner. I thought that was really useful. Would it be possible to add this again?

**Comment by alexandermendes** [comment]
:+1:

**Comment by adikeinan** [comment]
I still don't see the change - should I refresh anything or clear cache?

**Comment by alexandermendes** [comment]
It's there on the master branch, just had to sync it with the gh-pages branch, you should be able to see the change now.

**Comment by adikeinan** [comment]
Fantastic! Thank you!
