### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by adikeinan** [alexandermendes/tei-viewer#26]
Just a couple of suggestions - not at all critical:
1. Add an index field so that each line is numbered.
2. Enable deleting records from a current table view, e.g. via a checkbox next to each record and a 'Remove' button, or something of the sort
Feel free to ignore if this is too much work for now!

**Comment by alexandermendes** [comment]
Ah, I did mean to add a delete button, will get to it a bit later.

**Comment by alexandermendes** [comment]
:+1: https://github.com/alexandermendes/tei-viewer/pull/33
